         plankt_vari_vert_name( 1)= "            tempwz"
         plankt_vari_vert_name( 2)= "              vo2z" ! war(5)
         plankt_vari_vert_name( 3)= "             vnh4z" ! war(2)
         plankt_vari_vert_name( 4)= "             vno2z" ! war(3)
         plankt_vari_vert_name( 5)= "             vno3z" ! war(4)
         plankt_vari_vert_name( 6)= "             gelPz"
         plankt_vari_vert_name( 7)= "               Siz"
         plankt_vari_vert_name( 8)= "              akiz"
         plankt_vari_vert_name( 9)= "              agrz"
         plankt_vari_vert_name(10)= "              ablz"
         plankt_vari_vert_name(11)= "             chlaz"
         plankt_vari_vert_name(12)= "            hchlkz"
         plankt_vari_vert_name(13)= "            hchlgz"
         plankt_vari_vert_name(14)= "            hchlbz"
         plankt_vari_vert_name(15)= "            hgesPz" !auch tiefen-integriert, aber andere Nummer 
         plankt_vari_vert_name(16)= "            hgesNz" !auch tiefen-integriert, aber andere Nummer
         plankt_vari_vert_name(17)= "            hQ_NKz" ! sticktoff-Sattheit der Kieselalgen
         plankt_vari_vert_name(18)= "            hQ_NGz" !
         plankt_vari_vert_name(19)= "            hQ_NBz" !
         plankt_vari_vert_name(20)= "           hCChlkz" ! c-chla Verhältnis Kiesel entspricht akbcm
         plankt_vari_vert_name(21)= "           hCChlgz" !
         plankt_vari_vert_name(22)= "           hCChlbz" !
