! --------------------------------------------------------------------------- !
!  QSim - Programm zur Simulation der Wasserqualität                          !
!                                                                             !
!  Copyright (C) 2022                                                         !
!  Bundesanstalt für Gewässerkunde                                            !
!  Koblenz (Deutschland)                                                      !
!  http://www.bafg.de                                                         !
!                                                                             !
!  Dieses Programm ist freie Software. Sie können es unter den Bedingungen    !
!  der GNU General Public License, Version 3, wie von der Free Software       !
!  Foundation veröffentlicht, weitergeben und/oder modifizieren.              !
!                                                                             !
!  Die Veröffentlichung dieses Programms erfolgt in der Hoffnung, dass es     !
!  Ihnen von Nutzen sein wird, aber ohne irgendeine Garantie, sogar ohne die  !
!  implizite Garantie der Makrtreife oder der Verwendbarkeit für einen        !
!  bestimmten Zweck.                                                          !
!                                                                             !
!  Details finden Sie in der GNU General Public License.                      !
!  Sie sollten ein Exemplar der GNU General Public License zusammen mit       !
!  diesem Programm erhalten haben.                                            !
!  Falls nicht, siehe http://www.gnu.org/licenses/.                           !
!                                                                             !
!  Programmiert von                                                           !
!  1979 bis 2018   Volker Kirchesch                                           !
!  seit 2011       Jens Wyrwa, Wyrwa@bafg.de                                  !
! --------------------------------------------------------------------------- !

!> Write file ErgebMParam.xml
subroutine ErgebMParam(cpfad1)
   implicit none
   
   character(255), intent(in) :: cpfad1
   
   character (len=275)        :: pfadstring
   character (len = 8)        :: versionstext
   
   call version_string(versionstext)
   
   pfadstring =  trim(adjustl(cpfad1)) // 'ErgebMParam.xml'
   open(unit=1, file=pfadstring)
  
   write(1, '(A)') '<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>'
   write(1, '(A)') '<GerrisParam FileType="ErgebM" QsimVersion="13.42">'  
   
   write(1, '(A)') '<ParamSetDef Ident="ErgebM" Text="Tageswert-Ergebnis-Parameter" Help="Die von QSim als Tageswerte berechneten Parameter">'
   write(1, '(A)') '  <Parameter Ident="MIB5" Text="C-BSB5, Tages-Minimum" Unit="mg/l" Format="F6.2" Help="C-BSB5, Tages-Minimum" Group="Haupt" Quantity="BSB5" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XBSB5" Text="C-BSB5, Tagesmittelwert" Unit="mg/l" Format="F6.2" Help=" C-BSB5, Tagesmittelwert" Group="Haupt" Quantity="BSB5" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXB5" Text="C-BSB5, Tages-Maximum" Unit="mg/l" Format="F6.2" Help="C-BSB5, Tages-Maximum" Group="Haupt" Quantity="BSB5" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MICS" Text="CSB, Tages-Minimum" Unit="mg/l" Format="F6.2" Help="CSB, Tages-Minimum" Group="Haupt" Quantity="CSB" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XCSB" Text="CSB, Tagesmittelwert" Unit="mg/l" Format="F6.2" Help=" CSB, Tagesmittelwert" Group="Haupt" Quantity="CSB" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXCS" Text="CSB, Tages-Maximum" Unit="mg/l" Format="F6.2" Help="CSB, Tages-Maximum" Group="Haupt" Quantity="CSB" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MINH4" Text="NH4-N, Tages-Minimum" Unit="mg/l" Format="F6.2" Help="NH4-N, Tages-Minimum" Group="Haupt" Quantity="NH4" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XNH4" Text="NH4-N, Tagesmittelwert" Unit="mg/l" Format="F6.2" Help=" NH4-N, Tagesmittelwert" Group="Haupt" Quantity="NH4" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXNH4" Text="NH4-N, Tages-Maximum" Unit="mg/l" Format="F6.2" Help="NH4-N, Tages-Maximum" Group="Haupt" Quantity="NH4" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MIVNO2" Text="NO2-N, Tages-Minimum" Unit="mg/l" Format="F6.3" Help="NO2-N, Tages-Minimum" Group="Haupt" Quantity="NO2" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XVNO2" Text="NO2-N, Tagesmittelwert" Unit="mg/l" Format="F6.3" Help=" NO2-N, Tagesmittelwert" Group="Haupt" Quantity="NO2" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXVNO2" Text="NO2-N, Tages-Maximum" Unit="mg/l" Format="F6.3" Help="NO2-N, Tages-Maximum" Group="Haupt" Quantity="NO2" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MIVNO3" Text="NO3-N, Tages-Minimum" Unit="mg/l" Format="F9.6" Help="NO3-N, Tages-Minimum" Group="Haupt" Quantity="NO3" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XVNO3" Text="NO3-N, Tagesmittelwert" Unit="mg/l" Format="F9.6" Help=" NO3-N, Tagesmittelwert" Group="Haupt" Quantity="NO3" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXVNO3" Text="NO3-N, Tages-Maximum" Unit="mg/l" Format="F9.6" Help="NO3-N, Tages-Maximum" Group="Haupt" Quantity="NO3" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MIGSN" Text="gesN, Tages-Minimum" Unit="mg/l" Format="F5.2" Help="gesN, Tages-Minimum" Group="Haupt" Quantity="GSNY" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XGSN" Text="gesN, Tagesmittelwert" Unit="mg/l" Format="F5.2" Help=" gesN, Tagesmittelwert" Group="Haupt" Quantity="GSNY" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXGSN" Text="gesN, Tages-Maximum" Unit="mg/l" Format="F5.2" Help="gesN, Tages-Maximum" Group="Haupt" Quantity="GSNY" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MIGP" Text="o-PO4-P, Tages-Minimum" Unit="mg/l" Format="F6.3" Help="o-PO4-P, Tages-Minimum" Group="Haupt" Quantity="GELP" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XGELP" Text="o-PO4-P, Tagesmittelwert" Unit="mg/l" Format="F6.3" Help=" o-PO4-P, Tagesmittelwert" Group="Haupt" Quantity="GELP" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXGP" Text="o-PO4-P, Tages-Maximum" Unit="mg/l" Format="F6.3" Help="o-PO4-P, Tages-Maximum" Group="Haupt" Quantity="GELP" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MIGSP" Text="gesP, Tages-Minimum" Unit="mg/l" Format="F5.2" Help="ges P, Tages-Minimum" Group="Haupt" Quantity="GSPY" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XGSP" Text="gesP, Tagesmittelwert" Unit="mg/l" Format="F5.2" Help=" gesP, Tagesmittelwert" Group="Haupt" Quantity="GSPY" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXGSP" Text="gesP, Tages-Maximum" Unit="mg/l" Format="F5.2" Help="gesP, Tages-Maximum" Group="Haupt" Quantity="GSPY" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MISI" Text="gel Si, Tages-Minimum" Unit="mg/l" Format="F5.2" Help="gel Si, Tages-Minimum" Group="Haupt" Quantity="SI" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XSI" Text="gel Si, Tagesmittelwert" Unit="mg/l" Format="F5.2" Help=" gel Si, Tagesmittelwert" Group="Haupt" Quantity="SI" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXSI" Text="gel Si, Tages-Maximum" Unit="mg/l" Format="F5.2" Help="gel Si, Tages-Maximum" Group="Haupt" Quantity="SI" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MICHLA" Text="Chla, Tages-Minimum" Unit="µg/l" Format="F6.2" Help="Chla, Tages-Minimum" Group="Haupt" Quantity="CHLA" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XCHLA" Text="Chla, Tagesmittelwert" Unit="µg/l" Format="F6.2" Help=" Chla, Tagesmittelwert" Group="Haupt" Quantity="CHLA" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXCHLA" Text="Chla, Tages-Maximum" Unit="µg/l" Format="F6.2" Help="Chla, Tages-Maximum" Group="Haupt" Quantity="CHLA" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MIZO" Text="Zooplanktondichte, Tages-Minimum" Unit="Ind/l" Format="F7.1" Help="Zooplanktondichte, Tages-Minimum" Group="Haupt" Quantity="ZOOIND" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XZOOIND" Text="Zooplanktondichte, Tagesmittelwert" Unit="Ind/l" Format="F7.1" Help=" Zooplanktondichte, Tagesmittelwert" Group="Haupt" Quantity="ZOOIND" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXZO" Text="Zooplanktondichte, Tages-Maximum" Unit="Ind/l" Format="F7.1" Help="Zooplanktondichte, Tages-Maximum" Group="Haupt" Quantity="ZOOIND" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MIVPH" Text="pH-Wert, Tages-Minimum" Unit="-" Format="F5.2" Help="pH-Wert, Tages-Minimum" Group="Haupt" Quantity="PH" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XVPH" Text="pH-Wert, Tagesmittelwert" Unit="-" Format="F5.2" Help="pH-Wert, Tagesmittelwert" Group="Haupt" Quantity="PH" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXVPH" Text="pH-Wert, Tages-Maximum" Unit="-" Format="F5.2" Help="pH-Wert, Tages-Maximum" Group="Haupt" Quantity="PH" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MIMW" Text="m-Wert, Tages-Minimum" Unit="mmol/l" Format="F5.2" Help="m-Wert, Tages-Minimum" Group="Haupt" Quantity="MW" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XMW" Text="m-Wert, Tagesmittelwert" Unit="mmol/l" Format="F5.2" Help="m-Wert, Tagesmittelwert" Group="Haupt" Quantity="MW" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXMW" Text="m-Wert, Tages-Maximum" Unit="mmol/l" Format="F5.2" Help="m-Wert, Tages-Maximum" Group="Haupt" Quantity="MW" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MICA" Text="Ca, Tages-Minimum" Unit="mg/l" Format="F5.1" Help="Ca, Tages-Minimum" Group="Haupt" Quantity="CA" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XCA" Text="Ca, Tagesmittelwert" Unit="mg/l" Format="F5.1" Help="Ca, Tagesmittelwert" Group="Haupt" Quantity="CA" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXCA" Text="Ca, Tages-Maximum" Unit="mg/l" Format="F5.1" Help="Ca, Tages-Maximum" Group="Haupt" Quantity="CA" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MILF" Text="Leitfähigkeit, Tages-Minimum" Unit="µS/cm" Format="F8.1" Help="Leitfähigkeit, Tages-Minimum" Group="Haupt" Quantity="LF" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XLF" Text="Leitfähigkeit, Tagesmittelwert" Unit="µS/cm" Format="F8.1" Help="Leitfähigkeit, Tagesmittelwert" Group="Haupt" Quantity="LF" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXLF" Text="Leitfähigkeit, Tages-Maximum" Unit="µS/cm" Format="F8.1" Help="Leitfähigkeit, Tages-Maximum" Group="Haupt" Quantity="LF" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MISS" Text="Schwebstoffgehalt, Tages-Minimum" Unit="mg/l" Format="F8.2" Help="Schwebstoffgehalt, Tages-Minimum" Group="Haupt" Quantity="SS" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XSS" Text="Schwebstoffgehalt, Tagesmittelwert" Unit="mg/l" Format="F8.2" Help="Schwebstoffgehalt, Tagesmittelwert" Group="Haupt" Quantity="SS" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXSS" Text="Schwebstoffgehalt, Tages-Maximum" Unit="mg/l" Format="F8.2" Help="Schwebstoffgehalt, Tages-Maximum" Group="Haupt" Quantity="SS" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MITEMP" Text="Wassertemperatur, Tages-Minimum" Unit="°C" Format="F5.2" Help="Wassertemperatur, Tages-Minimum" Group="Haupt" Quantity="TEMPW" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XTEMP" Text="Wassertemperatur, Tagesmittelwert" Unit="°C" Format="F5.2" Help="Wassertemperatur, Tagesmittelwert" Group="Haupt" Quantity="TEMPW" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXTEMP" Text="Wassertemperatur, Tages-Maximum" Unit="°C" Format="F5.2" Help="Wassertemperatur, Tages-Maximum" Group="Haupt" Quantity="TEMPW" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MIO2" Text="Sauerstoffgehalt, Tages-Minimum" Unit="mg/l" Format="F5.2" Help="Sauerstoffgehalt, Tages-Minimum" Group="Haupt" Quantity="O2" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XO2" Text="Sauerstoffgehalt, Tagesmittelwert" Unit="mg/l" Format="F5.2" Help="Sauerstoffgehalt, Tagesmittelwert" Group="Haupt" Quantity="O2" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXO2" Text="Sauerstoffgehalt, Tages-Maximum" Unit="mg/l" Format="F5.2" Help="Sauerstoffgehalt, Tages-Maximum" Group="Haupt" Quantity="O2" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MICOLI" Text="fäkal coliforme Bakterien, Tages-Minimum" Unit="Ind/100 ml" Format="E9.2" Help="fäkal coliforme Bakterien, Tages-Minimum" Group="Haupt" Quantity="COLI" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XCOLI" Text="fäkal coliforme Bakterien, Tagesmittelwert" Unit="Ind/100 ml" Format="E9.2" Help="fäkal coliforme Bakterien, Tagesmittelwert" Group="Haupt" Quantity="COLI" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXCOLI" Text="fäkal coliforme Bakterien, Tages-Maximum" Unit="Ind/100 ml" Format="E9.2" Help="fäkal coliforme Bakterien, Tages-Maximum" Group="Haupt" Quantity="COLI" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MIKONSS" Text="konservative Substanz, Tages-Minimum" Unit="mg/l" Format="F7.1" Help="konservative Substanz, Tages-Minimum" Group="Haupt" Quantity="KONSS" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XKONSS" Text="konservative Substanz, Tagesmittelwert" Unit="mg/l" Format="F7.1" Help="konservative Substanz, Tagesmittelwert" Group="Haupt" Quantity="KONSS" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXKONSS" Text="konservative Substanz, Tages-Maximum" Unit="mg/l" Format="F7.1" Help="konservative Substanz, Tages-Maximum" Group="Haupt" Quantity="KONSS" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MIGSPB" Text="Blei-gesamt, Tages-Minimum" Unit="µg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="gsPb" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XGSPB" Text="Blei-gesamt, Tagesmittelwert" Unit="µg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="gsPb" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXGSPB" Text="Blei-gesamt, Tages-Maximum" Unit="µg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="gsPb" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MIGLPB" Text="Blei-gelöst, Tages-Minimum" Unit="µg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="glPb" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XGLPB" Text="Blei-gelöst, Tagesmittelwert" Unit="µg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="glPb" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXGLPB" Text="Blei-gelöst, Tages-Maximum" Unit="µg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="glPb" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MIGSCAD" Text="Cadmium-gesamt, Tages-Minimum" Unit="µg/l" Format="F7.3" Help="" Group="Schwermetalle" Quantity="gsCad" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XGSCAD" Text="Cadmium-gesamt, Tagesmittelwert" Unit="µg/l" Format="F7.3" Help="" Group="Schwermetalle" Quantity="gsCad" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXGSCAD" Text="Cadmium-gesamt, Tages-Maximum" Unit="µg/l" Format="F7.3" Help="" Group="Schwermetalle" Quantity="gsCad" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MIGLCAD" Text="Cadmium-gelöst, Tages-Minimum" Unit="µg/l" Format="F7.3" Help="" Group="Schwermetalle" Quantity="glCad" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XGLCAD" Text="Cadmium-gelöst, Tagesmittelwert" Unit="µg/l" Format="F7.3" Help="" Group="Schwermetalle" Quantity="glCad" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXGLCAD" Text="Cadmium-gelöst, Tages-Maximum" Unit="µg/l" Format="F7.3" Help="" Group="Schwermetalle" Quantity="glCad" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MIGSCR" Text="Chrom-gesamt, Tages-Minimum" Unit="µg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="gsCr" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XGSCR" Text="Chrom-gesamt, Tagesmittelwert" Unit="µg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="gsCr" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXGSCR" Text="Chrom-gesamt, Tages-Maximum" Unit="µg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="gsCr" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MIGLCR" Text="Chrom-gelöst, Tages-Minimum" Unit="µg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="glCr" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XGLCR" Text="Chrom-gelöst, Tagesmittelwert" Unit="µg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="glCr" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXGLCR" Text="Chrom-gelöst, Tages-Maximum" Unit="µg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="glCr" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MIGSFE" Text="Eisen-gesamt, Tages-Minimum" Unit="µg/l" Format="F8.1" Help="" Group="Schwermetalle" Quantity="gsFe" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XGSFE" Text="Eisen-gesamt, Tagesmittelwert" Unit="µg/l" Format="F8.1" Help="" Group="Schwermetalle" Quantity="gsFe" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXGSFE" Text="Eisen-gesamt, Tages-Maximum" Unit="µg/l" Format="F8.1" Help="" Group="Schwermetalle" Quantity="gsFe" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MIGLFE" Text="Eisen-gelöst, Tages-Minimum" Unit="µg/l" Format="F8.1" Help="" Group="Schwermetalle" Quantity="glFe" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XGLFE" Text="Eisen-gelöst, Tagesmittelwert" Unit="µg/l" Format="F8.1" Help="" Group="Schwermetalle" Quantity="glFe" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXGLFE" Text="Eisen-gelöst, Tages-Maximum" Unit="µg/l" Format="F8.1" Help="" Group="Schwermetalle" Quantity="glFe" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MIGSCU" Text="Kupfer-gesamt, Tages-Minimum" Unit="µg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="gsCu" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XGSCU" Text="Kupfer-gesamt, Tagesmittelwert" Unit="µg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="gsCu" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXGSCU" Text="Kupfer-gesamt, Tages-Maximum" Unit="µg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="gsCu" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MIGLCU" Text="Kupfer-gelöst, Tages-Minimum" Unit="µg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="glCu" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XGLCU" Text="Kupfer-gelöst, Tagesmittelwert" Unit="µg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="glCu" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXGLCU" Text="Kupfer-gelöst, Tages-Maximum" Unit="µg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="glCu" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MIGSMN" Text="Mangan-gesamt, Tages-Minimum" Unit="µg/l" Format="F8.1" Help="" Group="Schwermetalle" Quantity="gsMn" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XGSMN" Text="Mangan-gesamt, Tagesmittelwert" Unit="µg/l" Format="F8.1" Help="" Group="Schwermetalle" Quantity="gsMn" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXGSMN" Text="Mangan-gesamt, Tages-Maximum" Unit="µg/l" Format="F8.1" Help="" Group="Schwermetalle" Quantity="gsMn" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MIGLMN" Text="Mangan-gelöst, Tages-Minimum" Unit="µg/l" Format="F8.1" Help="" Group="Schwermetalle" Quantity="glMn" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XGLMN" Text="Mangan-gelöst, Tagesmittelwert" Unit="µg/l" Format="F8.1" Help="" Group="Schwermetalle" Quantity="glMn" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXGLMN" Text="Mangan-gelöst, Tages-Maximum" Unit="µg/l" Format="F8.1" Help="" Group="Schwermetalle" Quantity="glMn" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MIGSNI" Text="Nickel-gesamt, Tages-Minimum" Unit="µg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="gsNi" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XGSNI" Text="Nickel-gesamt, Tagesmittelwert" Unit="µg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="gsNi" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXGSNI" Text="Nickel-gesamt, Tages-Maximum" Unit="µg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="gsNi" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MIGLNI" Text="Nickel-gelöst, Tages-Minimum" Unit="µg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="glNi" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XGLNI" Text="Nickel-gelöst, Tagesmittelwert" Unit="µg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="glNi" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXGLNI" Text="Nickel-gelöst, Tages-Maximum" Unit="µg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="glNi" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MIGSHG" Text="Quecksilber-gesamt, Tages-Minimum" Unit="µg/l" Format="F7.3" Help="" Group="Schwermetalle" Quantity="gsHg" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XGSHG" Text="Quecksilber-gesamt, Tagesmittelwert" Unit="µg/l" Format="F7.3" Help="" Group="Schwermetalle" Quantity="gsHg" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXGSHG" Text="Quecksilber-gesamt, Tages-Maximum" Unit="µg/l" Format="F7.3" Help="" Group="Schwermetalle" Quantity="gsHg" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MIGLHG" Text="Quecksilber-gelöst, Tages-Minimum" Unit="µg/l" Format="F7.3" Help="" Group="Schwermetalle" Quantity="glHg" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XGLHG" Text="Quecksilber-gelöst, Tagesmittelwert" Unit="µg/l" Format="F7.3" Help="" Group="Schwermetalle" Quantity="glHg" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXGLHG" Text="Quecksilber-gelöst, Tages-Maximum" Unit="µg/l" Format="F7.3" Help="" Group="Schwermetalle" Quantity="glHg" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MIGSU" Text="Uran-gesamt, Tages-Minimum" Unit="µg/l" Format="F7.3" Help="" Group="Schwermetalle" Quantity="gsU" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XGSU" Text="Uran-gesamt, Tagesmittelwert" Unit="µg/l" Format="F7.3" Help="" Group="Schwermetalle" Quantity="gsU" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXGSU" Text="Uran-gesamt, Tages-Maximum" Unit="µg/l" Format="F7.3" Help="" Group="Schwermetalle" Quantity="gsU" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MIGLU" Text="Uran-gelöst, Tages-Minimum" Unit="µg/l" Format="F7.3" Help="" Group="Schwermetalle" Quantity="glU" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XGLU" Text="Uran-gelöst, Tagesmittelwert" Unit="µg/l" Format="F7.3" Help="" Group="Schwermetalle" Quantity="glU" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXGLU" Text="Uran-gelöst, Tages-Maximum" Unit="µg/l" Format="F7.3" Help="" Group="Schwermetalle" Quantity="glU" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MIGSZN" Text="Zink-gesamt, Tages-Minimum" Unit="µg/l" Format="F8.1" Help="" Group="Schwermetalle" Quantity="gsZn" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XGSZN" Text="Zink-gesamt, Tagesmittelwert" Unit="µg/l" Format="F8.1" Help="" Group="Schwermetalle" Quantity="gsZn" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXGSZN" Text="Zink-gesamt, Tages-Maximum" Unit="µg/l" Format="F8.1" Help="" Group="Schwermetalle" Quantity="gsZn" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MIGLZN" Text="Zink-gelöst, Tages-Minimum" Unit="µg/l" Format="F8.1" Help="" Group="Schwermetalle" Quantity="glZn" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XGLZN" Text="Zink-gelöst, Tagesmittelwert" Unit="µg/l" Format="F8.1" Help="" Group="Schwermetalle" Quantity="glZn" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXGLZN" Text="Zink-gelöst, Tages-Maximum" Unit="µg/l" Format="F8.1" Help="" Group="Schwermetalle" Quantity="glZn" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MIGSAS" Text="Arsen-gesamt, Tages-Minimum" Unit="µg/l" Format="F5.1" Help="" Group="Schwermetalle" Quantity="gsAs" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XGSAS" Text="Arsen-gesamt, Tagesmittelwert" Unit="µg/l" Format="F5.1" Help="" Group="Schwermetalle" Quantity="gsAs" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXGSAS" Text="Arsen-gesamt, Tages-Maximum" Unit="µg/l" Format="F5.1" Help="" Group="Schwermetalle" Quantity="gsAs" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="MIGLAS" Text="Arsen-gelöst, Tages-Minimum" Unit="µg/l" Format="F5.1" Help="" Group="Schwermetalle" Quantity="glAs" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="XGLAS" Text="Arsen-gelöst, Tagesmittelwert" Unit="µg/l" Format="F5.1" Help="" Group="Schwermetalle" Quantity="glAs" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="MXGLAS" Text="Arsen-gelöst, Tages-Maximum" Unit="µg/l" Format="F5.1" Help="" Group="Schwermetalle" Quantity="glAs" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="XPFL" Text="Makrophythenbiomasse, Tagesmittelwert" Unit="g/m²" Format="F7.2" Help="Makrophythenbiomasse, Tagesmittelwert" Group="Bio" Quantity="PFL" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="XBAL" Text="benthischen Algen, Tagesmittelwert" Unit="g/m²" Format="F7.2" Help="benthischen Algen, Tagesmittelwert" Group="Bio" Quantity="BAL" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="XDRBIO1" Text="Dreissenabiomasse (0. Kohorte), Tagesmittelwert" Unit="g/m²" Format="F7.2" Help="Dreissenabiomasse (0. Kohorte), Tagesmittelwert" Group="Bio" Quantity="DRBIO1" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="XGEWDR1" Text="Gewicht einer Muschel (0. Kohorte)" Unit="mg" Format="F7.2" Help="Gewicht einer Muschel (0. Kohorte)" Group="Bio" Quantity="GEWDR1" />'
   write(1, '(A)') '  <Parameter Ident="XDRBIO2" Text="Dreissenabiomasse (1. Kohorte), Tagesmittelwert" Unit="g/m²" Format="F7.2" Help="Dreissenabiomasse (1. Kohorte), Tagesmittelwert" Group="Bio" Quantity="DRBIO2" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="XGEWDR2" Text="Gewicht einer Muschel (1. Kohorte)" Unit="mg" Format="F7.2" Help="Gewicht einer Muschel (1. Kohorte)" Group="Bio" Quantity="GEWDR2" />'
   write(1, '(A)') '  <Parameter Ident="XDLARN" Text="Anzahl der Dreissena-Larven" Unit="Ind/l" Format="F7.2" Help="Anzahl der Dreissena-Larven" Group="Bio" Quantity="DLARN" />'
   write(1, '(A)') '  <Parameter Ident="XIDRAS1" Text="Ingestionsrate von Dreissena (0.Koh), Tagesmittelwert" Unit="1/d" Format="F6.3" Help="Ingestionsrate von Dreissena (0.Koh), Tagesmittelwert" Group="Bio" Quantity="IDRAS1" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="XIDRAS2" Text="Ingestionsrate von Dreissena (1.Koh), Tagesmittelwert" Unit="1/d" Format="F6.3" Help="Ingestionsrate von Dreissena (1.Koh), Tagesmittelwert" Group="Bio" Quantity="IDRAS2" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="XDRMAS1" Text="Wachstumsrate von Dreissena (0.Koh), Tagesmittelwert" Unit="1/d" Format="F6.3" Help="Wachstumsrate von Dreissena (0.Koh), Tagesmittelwert" Group="Bio" Quantity="DRMAS1" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="XDRMAS2" Text="Wachstumsrate von Dreissena (1.Koh), Tagesmittelwert" Unit="1/d" Format="F6.3" Help="Wachstumsrate von Dreissena (1.Koh), Tagesmittelwert" Group="Bio" Quantity="DRMAS2" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="XVOLDR" Text="Filtriertes Wasservolumen d. Dreissena" Unit="%" Format="F7.3" Help="Filtriertes Wasservolumen d. Dreissena" Group="Bio" Quantity="VOLDR" />'
   write(1, '(A)') '  <Parameter Ident="XDRAKR1" Text="aktive Respirationrate d Dreissena (0. Koh)" Unit="1/d" Format="F7.5" Help="aktive Respirationrate d Dreissena (0. Koh)" Group="Bio" Quantity="DRAKR1" />'
   write(1, '(A)') '  <Parameter Ident="XDRAKR2" Text="aktive Respirationrate d Dreissena (1. Koh)" Unit="1/d" Format="F7.5" Help="aktive Respirationrate d Dreissena (1. Koh)" Group="Bio" Quantity="DRAKR2" />'
   write(1, '(A)') '  <Parameter Ident="XDRBAR1" Text="Grundrespirationrate d. Dreissena (0. Koh)" Unit="1/d" Format="F7.5" Help="Grundrespirationrate d. Dreissena (0. Koh)" Group="Bio" Quantity="DRBAR1" />'
   write(1, '(A)') '  <Parameter Ident="XDRBAR2" Text="Grundrespirationrate d. Dreissena (1. Koh)" Unit="1/d" Format="F7.5" Help="Grundrespirationrate d. Dreissena (1. Koh)" Group="Bio" Quantity="DRBAR2" />'
   write(1, '(A)') '  <Parameter Ident="XDRMOR1" Text="Mortalitätsrate d. Dreissena (0.Koh)" Unit="1/d" Format="F7.5" Help="Mortalitätsrate d. Dreissena (0.Koh)" Group="Bio" Quantity="DRMOR1" />'
   write(1, '(A)') '  <Parameter Ident="XDRMOR2" Text="Mortalitätsrate d. Dreissena (1.Koh)" Unit="1/d" Format="F7.5" Help="Mortalitätsrate d. Dreissena (1.Koh)" Group="Bio" Quantity="DRMOR2" />'
   write(1, '(A)') '  <Parameter Ident="XFFOOD" Text="Verhältnis von Futterkonz. zu optimaler Futterkonzentration (Food-Faktor) für Dreissena" Unit="" Format="F5.3" Help="Verhältnis von Futterkonz. zu optimaler Futterkonzentration (Food-Faktor) für Dreissena" Group="Bio" Quantity="FFOOD" />'
   write(1, '(A)') '  <Parameter Ident="XCORI" Text="Corophiumdichte an der Böschung" Unit="Ind/l" Format="F8.1" Help="Corophiumdichte an der Böschung" Group="Bio" Quantity="CORI" />'
   write(1, '(A)') '  <Parameter Ident="XCORIS" Text="Corophiumdichte an der Sohle" Unit="Ind/l" Format="F8.1" Help="Corophiumdichte an der Sohle" Group="Bio" Quantity="CORIS" />'
   write(1, '(A)') '  <Parameter Ident="XAKIGR" Text="Gesamtbiomasse der Algen" Unit="mgC/l" Format="F6.2" Help="Gesamtbiomasse der Algen" Group="Bio" Quantity="AKIGR" />'
   write(1, '(A)') '  <Parameter Ident="XDALG" Text="mittlere Bruttoproduktionsrate der Algen" Unit="1/d" Format="F8.5" Help="mittlere Bruttoproduktionsrate der Algen" Group="Bio" Quantity="DALG" />'
   write(1, '(A)') '  <Parameter Ident="XDALGA" Text="mittlere Respirationsrate der Algen" Unit="1/d" Format="F8.5" Help="mittlere Respirationsrate der Algen" Group="Bio" Quantity="DALGA" />'
   write(1, '(A)') '  <Parameter Ident="XALMOR" Text="mittlere Mortalitätsrate der Algen" Unit="1/d" Format="F8.5" Help="mittlere Mortalitätsrate der Algen" Group="Bio" Quantity="ALMOR" />'
   write(1, '(A)') '  <Parameter Ident="XSEDAL" Text="mittlere Sedimentationsrate der Algen" Unit="1/d" Format="F8.5" Help="mittlere Sedimentationsrate der Algen" Group="Bio" Quantity="SEDAL" />'
   write(1, '(A)') '  <Parameter Ident="XALGZO" Text="mittlere Grazingrate durch Zooplankton" Unit="1/d" Format="F9.5" Help="mittlere Grazingrate durch Zooplankton" Group="Bio" Quantity="ALGZO" />'
   write(1, '(A)') '  <Parameter Ident="XALGDR" Text="mittlere Grazingrate durch Dreissena" Unit="1/d" Format="F9.5" Help="mittlere Grazingrate durch Dreissena" Group="Bio" Quantity="ALGDR" />'
   write(1, '(A)') '  <Parameter Ident="XDRPFE" Text="Mittlerer Pseudofacesanteil durch Dreissena" Unit="%" Format="F6.2" Help="Mittlerer Pseudofacesanteil durch Dreissena" Group="Bio" Quantity="DRPFE" />'
   write(1, '(A)') '  <Parameter Ident="XNAEHR" Text="Naehrstoffabhängigkeit bezogen auf Hellphase " Unit="[0...1]" Format="F5.2" Help="" Group="Bio" Quantity="" />'
   write(1, '(A)') '  <Parameter Ident="XVKIGR" Text="Verhältnis Kieselalgen/Grünalgen" Unit="[0..1]" Format="F5.2" Help="" Group="Bio" Quantity="VKIGR" />'
   write(1, '(A)') '  <Parameter Ident="XANTBL" Text="Anteil Blaualgen am Chla" Unit="[0..1]" Format="F5.2" Help="" Group="Bio" Quantity="ANTBL" />'
   write(1, '(A)') '  <Parameter Ident="XALGCO" Text="Algenverlust durch Corophium" Unit="" Format="F12.8" Help="" Group="Bio" Quantity="ALGCO" />'
   write(1, '(A)') '  <Parameter Ident="XFIK" Text="Lichtabhängigkeit der Algenproduktion bezogen auf Hellphase" Unit="[0...1]" Format="F5.2" Help="" Group="Bio" Quantity="FIK" />'
   write(1, '(A)') '  <Parameter Ident="XFIG" Text="Extinktionskoeffizient" Unit="1/m" Format="F5.2" Help="" Group="Bio" Quantity="FIG" />'
   write(1, '(A)') '  <Parameter Ident="XFIB" Text="leer" Unit="-1" Format="F5.2" Help="" Group="Bio" Quantity="FIB" />'
   write(1, '(A)') '  <Parameter Ident="XAKMUA" Text="Bruttowachstumsrate der Kieselalgen" Unit="1/d" Format="F6.3" Help="" Group="Bio" Quantity="AKMUA" />'
   write(1, '(A)') '  <Parameter Ident="XAGMUA" Text="Bruttowachstumsrate der Grünalgen" Unit="1/d" Format="F6.3" Help="" Group="Bio" Quantity="AGMUA" />'
   write(1, '(A)') '  <Parameter Ident="XABMUA" Text="Bruttowachstumsrate der Blaualgen" Unit="1/d" Format="F6.3" Help="" Group="Bio" Quantity="ABMUA" />'
   write(1, '(A)') '  <Parameter Ident="XFHEK" Text="Lichhemmung der Kieselalgen" Unit="[0..1]" Format="F6.3" Help="" Group="Bio" Quantity="FHEK" />'
   write(1, '(A)') '  <Parameter Ident="XFHEG" Text="Lichthemmung der Grünalgen" Unit="[0..1]" Format="F6.3" Help="" Group="Bio" Quantity="FHEG" />'
   write(1, '(A)') '  <Parameter Ident="XFHEB" Text="Lichthemmung der Blaualgen" Unit="[0..1]" Format="F6.3" Help="" Group="Bio" Quantity="FHEB" />'
   write(1, '(A)') '  <Parameter Ident="XAKRAU" Text="Respirationsrate der Kieselalgen" Unit="1/d" Format="F6.3" Help="" Group="Bio" Quantity="AKRAU" />'
   write(1, '(A)') '  <Parameter Ident="XAGREA" Text="Respirationsrate der Grünalgen" Unit="1/d" Format="F6.3" Help="" Group="Bio" Quantity="AGREA" />'
   write(1, '(A)') '  <Parameter Ident="XABREA" Text="Respiration der Blaualgen" Unit="1/d" Format="F6.3" Help="" Group="Bio" Quantity="ABREA" />'
   write(1, '(A)') '  <Parameter Ident="XCHLAK" Text="Chla-Gehalt der Kieselalgen" Unit="µg/l" Format="F6.1" Help="" Group="Bio" Quantity="CHLAK" />'
   write(1, '(A)') '  <Parameter Ident="XCHLAG" Text="Chla-Gehalt der Grünalgen" Unit="µg/l" Format="F6.1" Help="" Group="Bio" Quantity="CHLAG" />'
   write(1, '(A)') '  <Parameter Ident="XCHLAB" Text="Chla-Gehalt der Blaualgen" Unit="µg/l" Format="F6.1" Help="" Group="Bio" Quantity="CHLAB" />'
   write(1, '(A)') '  <Parameter Ident="XCCHLK" Text="C:Chla-Verhältnis der Kieselalgen" Unit="mg/mg" Format="F6.2" Help="" Group="Bio" Quantity="CCHLK" />'
   write(1, '(A)') '  <Parameter Ident="XCCHLG" Text="C:Chla-Verhältnis der Grünalgen" Unit="mg/mg" Format="F6.2" Help="" Group="Bio" Quantity="CCHLG" />'
   write(1, '(A)') '  <Parameter Ident="XCCHLB" Text="C:Chla-Verhältnis der Blaualgen" Unit="mg/mg" Format="F6.2" Help="" Group="Bio" Quantity="CCHLB" />'
   write(1, '(A)') '  <Parameter Ident="XIR" Text="Ingestionsrate des Zooplanktons" Unit="1/d" Format="F6.3" Help="Ingestionsrate des Zooplanktons" Group="Bio" Quantity="IR" />'
   write(1, '(A)') '  <Parameter Ident="XRMUE" Text="Wachstumsrate des Zooplanktons" Unit="1/d" Format="F6.3" Help="Wachstumsrate des Zooplanktons" Group="Bio" Quantity="RMUE" />'
   write(1, '(A)') '  <Parameter Ident="XRAKR" Text="Aktive Respirationsrate des Zooplanktons" Unit="1/d" Format="F6.4" Help="Aktive Respirationsrate des Zooplanktons" Group="Bio" Quantity="RAKR" />'
   write(1, '(A)') '  <Parameter Ident="XRBAR" Text="Basale Respirationsrate des Zooplanktons" Unit="1/d" Format="F6.4" Help="Basale Respirationsrate des Zooplanktons" Group="Bio" Quantity="RBAR" />'
   write(1, '(A)') '  <Parameter Ident="CBSBAB" Text="Abwasserbürtiger C-BSB5" Unit="mg/l" Format="F6.3" Help="Abwasserbürtiger C-BSB5" Group="Bio" Quantity="" />'
   write(1, '(A)') '  <Parameter Ident="ABBAU" Text="Abbaugrad" Unit="-" Format="F5.3" Help="Abbaugrad" Group="Bio" Quantity="" />'
   write(1, '(A)') '  <Parameter Ident="XCM" Text="Konzentration an monomolekularen C-Verbindungen" Unit="mgC/l" Format="F6.3" Help="Konzentration an monomolekularen C-Verbindungen" Group="Bio" Quantity="CM" />'
   write(1, '(A)') '  <Parameter Ident="XBAC" Text="Heterotrophe Bakterienbiomasse" Unit="mgC/l" Format="F6.3" Help="Heterotrophe Bakterienbiomasse" Group="Bio" Quantity="BAC" />'
   write(1, '(A)') '  <Parameter Ident="XCD1" Text="Konzentration an gelösten leichtabbaubaren C-Verbindungen" Unit="mgC/l" Format="F7.3" Help="Konzentration an gelösten leichtabbaubaren C-Verbindungen" Group="Bio" Quantity="CD1" />'
   write(1, '(A)') '  <Parameter Ident="XCD2" Text="Konzentration an gelösten schwerabbaubaren C-Verbindungen" Unit="mgC/l" Format="F7.3" Help="Konzentration an gelösten schwerabbaubaren C-Verbindungen" Group="Bio" Quantity="CD2" />'
   write(1, '(A)') '  <Parameter Ident="XCP1" Text="Konzentration an partikulären leichtabbaubaren C-Verbindungen" Unit="mgC/l" Format="F7.3" Help="" Group="Bio" Quantity="CP1" />'
   write(1, '(A)') '  <Parameter Ident="XCP2" Text="Konzentration an partikulären  schwerabbaubaren  C-Verbindungen" Unit="mgC/l" Format="F7.3" Help="" Group="Bio" Quantity="CP2" />'
   write(1, '(A)') '  <Parameter Ident="XBACMU" Text="Wachstumsrate der Bakterien" Unit="1/d" Format="F6.3" Help="" Group="Bio" Quantity="BACMU" />'
   write(1, '(A)') '  <Parameter Ident="XHNFBA" Text="Verlustrate d. BAC d. Flagellaten" Unit="1/d" Format="F6.3" Help="" Group="Bio" Quantity="HNFBA" />'
   write(1, '(A)') '  <Parameter Ident="XCHNFI" Text="Flagellatendichte" Unit="Ind/ml" Format="F8.1" Help="Flagellatendichte" Group="Bio" Quantity="CHNFI" />'
   write(1, '(A)') '  <Parameter Ident="XCHNF" Text="Biomasse der Flagellaten" Unit="µgC/l" Format="F7.3" Help="Biomasse der Flagellaten" Group="Bio" Quantity="CHNF" />'
   write(1, '(A)') '  <Parameter Ident="XHNFUP" Text="Aufnahmerate der Flagellaten" Unit="1/d" Format="F6.3" Help="Aufnahmerate der Flagellaten" Group="Bio" Quantity="HNFUP" />'
   write(1, '(A)') '  <Parameter Ident="XHNFRE" Text="Respirationsrate der Flagellaten" Unit="1/d" Format="F6.3" Help="Respirationsrate der Flagellaten" Group="Bio" Quantity="HNFRE" />'
   write(1, '(A)') '  <Parameter Ident="XHNFEX" Text="Exkretionsrate der Flagellaten" Unit="1/d" Format="F6.3" Help="Exkretionsrate der Flagellaten" Group="Bio" Quantity="HNFEX" />'
   write(1, '(A)') '  <Parameter Ident="XHNFMO" Text="Mortalitätsrate der Flagellaten" Unit="1/d" Format="F6.3" Help="" Group="Bio" Quantity="HNFMO" />'
   write(1, '(A)') '  <Parameter Ident="XHNFMU" Text="Wachstumsrate der Flagellaten" Unit="1/d" Format="F6.3" Help="" Group="Bio" Quantity="HNFMU" />'
   write(1, '(A)') '  <Parameter Ident="XHNFZ" Text="Flagellatenverlustrate durch Rotatorien" Unit="1/d" Format="F6.3" Help="" Group="Bio" Quantity="HNFZ" />'
   write(1, '(A)') '  <Parameter Ident="XHNFDR" Text="Flagellatenverlustrate durch Dreissena" Unit="1/d" Format="F6.3" Help="" Group="Bio" Quantity="HNFDR" />'
   write(1, '(A)') '  <Parameter Ident="XSUSN" Text="Umsatzrate der susp. Nitrosomonas" Unit="mgN/(l*h)" Format="F7.5" Help="Umsatzrate der susp. Nitrosomonas" Group="Bio" Quantity="SUSN" />'
   write(1, '(A)') '  <Parameter Ident="XBETTN" Text="AmmoniumFlux Wasser/Sediment (-)" Unit="mgN/(l*h)" Format="F10.8" Help="Umsatzrate der sessilen Nitrosomonas" Group="Bio" Quantity="BETTN" />'
   write(1, '(A)') '  <Parameter Ident="XDON" Text="NH4-N-Nachlieferung beim C-Abbau" Unit="mgN/(l*h)" Format="F7.5" Help="NH4-N-Nachlieferung beim C-Abbau" Group="Bio" Quantity="DON" />'
   write(1, '(A)') '  <Parameter Ident="XALGN" Text="NH4-Verbrauch durch Algen" Unit="mgN/(l*h)" Format="F7.5" Help="N-Verbrauch durch Algen" Group="Bio" Quantity="ALGN" />'
   write(1, '(A)') '  <Parameter Ident="xalNO3" Text="NO3-Verbrauch durch Algen" Unit="mgN/(l*h)" Format="F7.5" Help="" Group="Bio" Quantity="ALNO3" />'
   write(1, '(A)') '  <Parameter Ident="xFluN3" Text="Nitratänderung im Wasserkörper durch das Sediment" Unit="mgN/(l*h)" Format="F10.7" Help="NitratFlux in (-) aus (+) dem Sediment" Group="Bio" Quantity="FluxN4" />'
   write(1, '(A)') '  <Parameter Ident="xJNO3" Text="Nitratflux Wasser/Sediment (-)" Unit="gN/(m2*d)" Format="F10.8" Help="" Group="Bio" Quantity="" />'
   write(1, '(A)') '  <Parameter Ident="xJNH4" Text="Ammoniumflux Wasser/Sediment (-)" Unit="gN/(m2*d)" Format="F10.8" Help="" Group="Bio" Quantity="" />'
   write(1, '(A)') '  <Parameter Ident="XVX0" Text="Biomasse der Nitrosomonas" Unit="µg/l" Format="F8.5" Help="Biomasse der Nitrosomonas" Group="Bio" Quantity="VX0" />'
   write(1, '(A)') '  <Parameter Ident="XSEDX" Text="Sedimentationsrate der Nitrosomonas" Unit="mgBio/(l*h)" Format="F6.3" Help="Sedimentationsrate der Nitrosomonas" Group="Bio" Quantity="SEDX" />'
   write(1, '(A)') '  <Parameter Ident="XVX02" Text="Biomasse der Nitrobacter" Unit="µg/l" Format="F8.5" Help="Biomasse der Nitrobacter" Group="Bio" Quantity="VX02" />'
   write(1, '(A)') '  <Parameter Ident="xJPO4" Text="P-Flux Wasser/Sediment(-)" Unit="gP/(m2*d)" Format="F10.8" Help="" Group="Bio" Quantity="" />'
   write(1, '(A)') '  <Parameter Ident="xJSi" Text="Si-Flux Wasser/Sediment(-)" Unit="gSi/(m2*d)" Format="F10.8" Help="" Group="Bio" Quantity="" />'
   write(1, '(A)') '  <Parameter Ident="XO2NIT" Text="Sauerstoffverbrauch durch Nitrifikation" Unit="mgO2/(l*h)" Format="F7.4" Help="Sauerstoffverbrauch durch Nitrifikation" Group="Bio" Quantity="O2NIT" />'
   write(1, '(A)') '  <Parameter Ident="XALGO" Text="Bruttosauerstoffproduktion durch Algen" Unit="mgO2/(l*h)" Format="F7.4" Help="Bruttosauerstoffproduktion durch Algen" Group="Bio" Quantity="ALGO" />'
   write(1, '(A)') '  <Parameter Ident="XALGAO" Text="Sauerstoffverbrauch durch Algenrespiration" Unit="mgO2/(l*h)" Format="F7.4" Help="Sauerstoffverbrauch durch Algenrespiration" Group="Bio" Quantity="ALGAO" />'
   write(1, '(A)') '  <Parameter Ident="XBSBT" Text="Sauerstoffverbrauch durch BSB-Abbau" Unit="mgO2/(l*h)" Format="F7.4" Help="" Group="Bio" Quantity="BSBT" />'
   write(1, '(A)') '  <Parameter Ident="XSCHLR" Text="SauerstoffFlux Wasser/Sediment (+)" Unit="mgO2/(l*h)" Format="F10.8" Help="Sauerstoffverbrauch durch Bodenschlamm" Group="Bio" Quantity="SCHLR" />'
   write(1, '(A)') '  <Parameter Ident="xJO2" Text="SauerstoffFlux Wasser/Sediment(+)" Unit="gO2/(m2*d)" Format="F10.8" Help="" Group="Bio" Quantity="" />'
   write(1, '(A)') '  <Parameter Ident="XBSBBE" Text="Sauerstoffverbrauch durch sessilen BSB-Abbau" Unit="mgO2/(l*h)" Format="F7.4" Help="" Group="Bio" Quantity="BSBBE" />'
   write(1, '(A)') '  <Parameter Ident="XO2PHY" Text="physikalischer Sauerstoffeintrag" Unit="mgO2/(l*h)" Format="F7.4" Help="" Group="Bio" Quantity="O2PHY" />'
   write(1, '(A)') '  <Parameter Ident="XABEOW" Text="Sauerstoffproduktion durch benthische Algen" Unit="mgO2/(l*h)" Format="F7.4" Help="" Group="Bio" Quantity="ABEOW" />'
   write(1, '(A)') '  <Parameter Ident="XABEOR" Text="Sauerstoffverbrauch durch benthische Algen" Unit="mgO2/(l*h)" Format="F7.4" Help="" Group="Bio" Quantity="ABEOR" />'
   write(1, '(A)') '  <Parameter Ident="XRO2DR" Text="Sauerstoffverbrauch durch Dreissena" Unit="mgO2/(l*h)" Format="F7.4" Help="" Group="Bio" Quantity="RO2DR" />'
   write(1, '(A)') '  <Parameter Ident="XZOORO" Text="Sauerstoffverbrauch durch Zooplankter" Unit="mgO2/(l*h)" Format="F7.4" Help="" Group="Bio" Quantity="ZOORO" />'
   write(1, '(A)') '  <Parameter Ident="XPO2P" Text="Sauerstoffproduktion durch Makrophyten" Unit="mgO2/(l*h)" Format="F7.4" Help="" Group="Bio" Quantity="PO2P" />'
   write(1, '(A)') '  <Parameter Ident="XPO2R" Text="Sauerstoffverbrauch durch Makrophyten" Unit="mgO2/(l*h)" Format="F7.4" Help="" Group="Bio" Quantity="PO2R" />'
   write(1, '(A)') '  <Parameter Ident="SEDHY" Text="Sedimenthöhe" Unit="mm" Format="F12.6" Help="" Group="Sediment" Quantity="SEDHY" />'
   write(1, '(A)') '  <Parameter Ident="BMIBSB" Text="C-BSB5 im Buhnenfeld, Tages-Minimum" Unit="mg/l" Format="F6.2" Help="C-BSB5 im Buhnenfeld, Tages-Minimum" Group="Buhne" Quantity="BBSB5" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXBSB5" Text="C-BSB5 im Buhnenfeld, Tagesmittelwert" Unit="mg/l" Format="F6.2" Help=" C-BSB5 im Buhnenfeld, Tagesmittelwert" Group="Buhne" Quantity="BBSB5" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXBSB" Text="C-BSB5 im Buhnenfeld, Tages-Maximum" Unit="mg/l" Format="F6.2" Help="C-BSB5 im Buhnenfeld, Tages-Maximum" Group="Buhne" Quantity="BBSB5" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BMICSB" Text="CSB im Buhnenfeld, Tages-Minimum" Unit="mg/l" Format="F6.2" Help="CSB im Buhnenfeld, Tages-Minimum" Group="Buhne" Quantity="BCSB" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXCSB" Text="CSB im Buhnenfeld, Tagesmittelwert" Unit="mg/l" Format="F6.2" Help=" CSB im Buhnenfeld, Tagesmittelwert" Group="Buhne" Quantity="BCSB" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXCSB" Text="CSB im Buhnenfeld, Tages-Maximum" Unit="mg/l" Format="F6.2" Help="CSB im Buhnenfeld, Tages-Maximum" Group="Buhne" Quantity="BCSB" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BMINH4" Text="NH4-N im Buhnenfeld, Tages-Minimum" Unit="mg/l" Format="F6.2" Help="NH4-N im Buhnenfeld, Tages-Minimum" Group="Buhne" Quantity="BNH4" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXNH4" Text="NH4-N im Buhnenfeld, Tagesmittelwert" Unit="mg/l" Format="F6.2" Help=" NH4-N im Buhnenfeld, Tagesmittelwert" Group="Buhne" Quantity="NH4" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXNH4" Text="NH4-N im Buhnenfeld, Tages-Maximum" Unit="mg/l" Format="F6.2" Help="NH4-N im Buhnenfeld, Tages-Maximum" Group="Buhne" Quantity="NH4" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BMINO2" Text="NO2-N im Buhnenfeld, Tages-Minimum" Unit="mg/l" Format="F6.3" Help="NO2-N im Buhnenfeld, Tages-Minimum" Group="Buhne" Quantity="NO2" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXNO2" Text="NO2-N im Buhnenfeld, Tagesmittelwert" Unit="mg/l" Format="F6.3" Help=" NO2-N im Buhnenfeld, Tagesmittelwert" Group="Buhne" Quantity="NO2" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXNO2" Text="NO2-N im Buhnenfeld, Tages-Maximum" Unit="mg/l" Format="F6.3" Help="NO2-N im Buhnenfeld, Tages-Maximum" Group="Buhne" Quantity="NO2" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BMINO3" Text="NO3-N im Buhnenfeld, Tages-Minimum" Unit="mg/l" Format="F9.6" Help="NO3-N im Buhnenfeld, Tages-Minimum" Group="Buhne" Quantity="NO3" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXNO3" Text="NO3-N im Buhnenfeld, Tagesmittelwert" Unit="mg/l" Format="F9.6" Help=" NO3-N im Buhnenfeld, Tagesmittelwert" Group="Buhne" Quantity="NO3" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXNO3" Text="NO3-N im Buhnenfeld, Tages-Maximum" Unit="mg/l" Format="F9.6" Help="NO3-N im Buhnenfeld, Tages-Maximum" Group="Buhne" Quantity="NO3" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BMIGSN" Text="gesN im Buhnenfeld, Tages-Minimum" Unit="mg/l" Format="F5.2" Help="gesN im Buhnenfeld, Tages-Minimum" Group="Buhne" Quantity="GSN" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXGSN" Text="gesN im Buhnenfeld, Tagesmittelwert" Unit="mg/l" Format="F5.2" Help=" gesN im Buhnenfeld, Tagesmittelwert" Group="Buhne" Quantity="GSN" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXGSN" Text="gesN im Buhnenfeld, Tages-Maximum" Unit="mg/l" Format="F5.2" Help="gesN im Buhnenfeld, Tages-Maximum" Group="Buhne" Quantity="GSN" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BMIGLP" Text="o-PO4-P im Buhnenfeld, Tages-Minimum" Unit="mg/l" Format="F6.3" Help="o-PO4-P im Buhnenfeld, Tages-Minimum" Group="Buhne" Quantity="GLP" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXGELP" Text="o-PO4-P im Buhnenfeld, Tagesmittelwert" Unit="mg/l" Format="F6.3" Help=" o-PO4-P im Buhnenfeld, Tagesmittelwert" Group="Buhne" Quantity="GELP" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXGLP" Text="o-PO4-P im Buhnenfeld, Tages-Maximum" Unit="mg/l" Format="F6.3" Help="o-PO4-P im Buhnenfeld, Tages-Maximum" Group="Buhne" Quantity="GLP" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BMIGSP" Text="ges P im Buhnenfeld, Tages-Minimum" Unit="mg/l" Format="F5.2" Help="ges P im Buhnenfeld, Tages-Minimum" Group="Buhne" Quantity="GSP" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXGSP" Text="gesP im Buhnenfeld, Tagesmittelwert" Unit="mg/l" Format="F5.2" Help=" gesP im Buhnenfeld, Tagesmittelwert" Group="Buhne" Quantity="GSP" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXGSP" Text="gesP im Buhnenfeld, Tages-Maximum" Unit="mg/l" Format="F5.2" Help="gesP im Buhnenfeld, Tages-Maximum" Group="Buhne" Quantity="GSP" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BMISI" Text="gel Si im Buhnenfeld, Tages-Minimum" Unit="mg/l" Format="F5.2" Help="gel Si im Buhnenfeld, Tages-Minimum" Group="Buhne" Quantity="SI" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXSI" Text="gel Si im Buhnenfeld, Tagesmittelwert" Unit="mg/l" Format="F5.2" Help=" gel Si im Buhnenfeld, Tagesmittelwert" Group="Buhne" Quantity="SI" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXSI" Text="gel Si im Buhnenfeld, Tages-Maximum" Unit="mg/l" Format="F5.2" Help="gel Si im Buhnenfeld, Tages-Maximum" Group="Buhne" Quantity="SI" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BMICHL" Text="Chla im Buhnenfeld, Tages-Minimum" Unit="µg/l" Format="F6.2" Help="Chla im Buhnenfeld, Tages-Minimum" Group="Buhne" Quantity="CHL" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXCHLA" Text="Chla im Buhnenfeld, Tagesmittelwert" Unit="µg/l" Format="F6.2" Help=" Chla im Buhnenfeld, Tagesmittelwert" Group="Buhne" Quantity="CHLA" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXCHL" Text="Chla im Buhnenfeld, Tages-Maximum" Unit="µg/l" Format="F6.2" Help="Chla im Buhnenfeld, Tages-Maximum" Group="Buhne" Quantity="CHL" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BMIZOO" Text="Zooplanktondichte im Buhnenfeld, Tages-Minimum" Unit="Ind/l" Format="F7.1" Help="Zooplanktondichte im Buhnenfeld, Tages-Minimum" Group="Buhne" Quantity="ZOO" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXZOOI" Text="Zooplanktondichte im Buhnenfeld, Tagesmittelwert" Unit="Ind/l" Format="F7.1" Help=" Zooplanktondichte im Buhnenfeld, Tagesmittelwert" Group="Buhne" Quantity="ZOOI" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXZOO" Text="Zooplanktondichte im Buhnenfeld, Tages-Maximum" Unit="Ind/l" Format="F7.1" Help="Zooplanktondichte im Buhnenfeld, Tages-Maximum" Group="Buhne" Quantity="ZOO" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BMIPH" Text="pH-Wertes im Buhnenfeld, Tages-Minimum" Unit="[-]" Format="F5.2" Help="pH-Wertes im Buhnenfeld, Tages-Minimum" Group="Buhne" Quantity="PH" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXPH" Text="pH-Wertes im Buhnenfeld, Tagesmittelwert" Unit="[-]" Format="F5.2" Help="pH-Wertes im Buhnenfeld, Tagesmittelwert" Group="Buhne" Quantity="PH" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXPH" Text="pH-Wertes im Buhnenfeld, Tages-Maximum" Unit="[-]" Format="F5.2" Help="pH-Wertes im Buhnenfeld, Tages-Maximum" Group="Buhne" Quantity="PH" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BMIMW" Text="m-Wertes im Buhnenfeld, Tages-Minimum" Unit="mmol/l" Format="F5.2" Help="m-Wertes im Buhnenfeld, Tages-Minimum" Group="Buhne" Quantity="MW" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXMW" Text="m-Wertes im Buhnenfeld, Tagesmittelwert" Unit="mmol/l" Format="F5.2" Help="m-Wertes im Buhnenfeld, Tagesmittelwert" Group="Buhne" Quantity="MW" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXMW" Text="m-Wertes im Buhnenfeld, Tages-Maximum" Unit="mmol/l" Format="F5.2" Help="m-Wertes im Buhnenfeld, Tages-Maximum" Group="Buhne" Quantity="MW" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BMICA" Text="Ca im Buhnenfeld, Tages-Minimum" Unit="mg/l" Format="F5.1" Help="Ca im Buhnenfeld, Tages-Minimum" Group="Buhne" Quantity="CA" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXCA" Text="Ca im Buhnenfeld, Tagesmittelwert" Unit="mg/l" Format="F5.1" Help="Ca im Buhnenfeld, Tagesmittelwert" Group="Buhne" Quantity="CA" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXCA" Text="Ca im Buhnenfeld, Tages-Maximum" Unit="mg/l" Format="F5.1" Help="Ca im Buhnenfeld, Tages-Maximum" Group="Buhne" Quantity="CA" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BMILF" Text="Leitfähigkeit im Buhnenfeld, Tages-Minimum" Unit="µS/cm" Format="F8.1" Help="Leitfähigkeit im Buhnenfeld, Tages-Minimum" Group="Buhne" Quantity="LF" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXLF" Text="Leitfähigkeit im Buhnenfeld, Tagesmittelwert" Unit="µS/cm" Format="F8.1" Help="Leitfähigkeit im Buhnenfeld, Tagesmittelwert" Group="Buhne" Quantity="LF" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXLF" Text="Leitfähigkeit im Buhnenfeld, Tages-Maximum" Unit="µS/cm" Format="F8.1" Help="Leitfähigkeit im Buhnenfeld, Tages-Maximum" Group="Buhne" Quantity="LF" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BMISSA" Text="Schwebstoffgehalts im Buhnenfeld, Tages-Minimum" Unit="mg/l" Format="F6.2" Help="Schwebstoffgehalts im Buhnenfeld, Tages-Minimum" Group="Buhne" Quantity="SSA" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXSSAL" Text="Schwebstoffgehalts im Buhnenfeld, Tagesmittelwert" Unit="mg/l" Format="F6.2" Help="Schwebstoffgehalts im Buhnenfeld, Tagesmittelwert" Group="Buhne" Quantity="SSAL" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXSSA" Text="Schwebstoffgehalts im Buhnenfeld, Tages-Maximum" Unit="mg/l" Format="F6.2" Help="Schwebstoffgehalts im Buhnenfeld, Tages-Maximum" Group="Buhne" Quantity="SSA" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BMITEM" Text="Wassertemperatur im Buhnenfeld, Tages-Minimum" Unit="°C" Format="F5.2" Help="Wassertemperatur im Buhnenfeld, Tages-Minimum" Group="Buhne" Quantity="TEM" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXTEMP" Text="Wassertemperatur im Buhnenfeld, Tagesmittelwert" Unit="°C" Format="F5.2" Help="Wassertemperatur im Buhnenfeld, Tagesmittelwert" Group="Buhne" Quantity="TEMP" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXTEM" Text="Wassertemperatur im Buhnenfeld, Tages-Maximum" Unit="°C" Format="F5.2" Help="Wassertemperatur im Buhnenfeld, Tages-Maximum" Group="Buhne" Quantity="TEM" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BMIO2" Text="Sauerstoffgehalts im Buhnenfeld, Tages-Minimum" Unit="mg/l" Format="F5.2" Help="Sauerstoffgehalts im Buhnenfeld, Tages-Minimum" Group="Buhne" Quantity="O2" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXO2" Text="Sauerstoffgehalts im Buhnenfeld, Tagesmittelwert" Unit="mg/l" Format="F5.2" Help="Sauerstoffgehalts im Buhnenfeld, Tagesmittelwert" Group="Buhne" Quantity="O2" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXO2" Text="Sauerstoffgehalts im Buhnenfeld, Tages-Maximum" Unit="mg/l" Format="F5.2" Help="Sauerstoffgehalts im Buhnenfeld, Tages-Maximum" Group="Buhne" Quantity="O2" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BXMICL" Text="Colibakterien im Buhnenfeld, Tagesmittelwert" Unit="Ind/100 ml" Format="F8.0" Help="" Group="Buhne" Quantity="MICL" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BXCOLI" Text="Colibakterien im Buhnenfeld, Tagesmittelwert" Unit="Ind/100 ml" Format="F8.0" Help="" Group="Buhne" Quantity="COLI" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BXMXCL" Text="Colibakterien im Buhnenfeld, Tagesmittelwert" Unit="Ind/100 ml" Format="F8.0" Help="" Group="Buhne" Quantity="MXCL" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMIKONSS" Text="konservative Substanz im Buhnenfeld, Tages-Minimum" Unit="mg/l" Format="F7.1" Help="konservative Substanz, Tages-Minimum" Group="Buhne" Quantity="KONSS" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXKONSS" Text="konservative Substanz im Buhnenfeld, Tagesmittelwert" Unit="mg/l" Format="F7.1" Help="konservative Substanz, Tagesmittelwert" Group="Buhne" Quantity="KONSS" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXKONSS" Text="konservative Substanz im Buhnenfeld, Tages-Maximum" Unit="mg/l" Format="F7.1" Help="konservative Substanz, Tages-Maximum" Group="Buhne" Quantity="KONSS" Aggregat="Max" />'

   write(1, '(A)') '  <Parameter Ident="BMIGSPB" Text="Blei-gesamt im Buhnenfeld, Tages-Minimum" Unit="mg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="gsPb" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXGSPB" Text="Blei-gesamt im Buhnenfeld, Tagesmittelwert" Unit="mg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="gsPb" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXGSPB" Text="Blei-gesamt im Buhnenfeld, Tages-Maximum" Unit="mg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="gsPb" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BMIGLPB" Text="Blei-gelöst im Buhnenfeld, Tages-Minimum" Unit="mg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="glPb" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXGLPB" Text="Blei-gelöst im Buhnenfeld, Tagesmittelwert" Unit="mg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="glPb" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXGLPB" Text="Blei-gelöst im Buhnenfeld, Tages-Maximum" Unit="mg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="glPb" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BMIGSCAD" Text="Cadmium-gesamt im Buhnenfeld, Tages-Minimum" Unit="mg/l" Format="F7.3" Help="" Group="Schwermetalle" Quantity="gsCad" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXGSCAD" Text="Cadmium-gesamt im Buhnenfeld, Tagesmittelwert" Unit="mg/l" Format="F7.3" Help="" Group="Schwermetalle" Quantity="gsCad" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXGSCAD" Text="Cadmium-gesamt im Buhnenfeld, Tages-Maximum" Unit="mg/l" Format="F7.3" Help="" Group="Schwermetalle" Quantity="gsCad" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BMIGLCAD" Text="Cadmium-gelöst im Buhnenfeld, Tages-Minimum" Unit="mg/l" Format="F7.3" Help="" Group="Schwermetalle" Quantity="glCad" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXGLCAD" Text="Cadmium-gelöst im Buhnenfeld, Tagesmittelwert" Unit="mg/l" Format="F7.3" Help="" Group="Schwermetalle" Quantity="glCad" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXGLCAD" Text="Cadmium-gelöst im Buhnenfeld, Tages-Maximum" Unit="mg/l" Format="F7.3" Help="" Group="Schwermetalle" Quantity="glCad" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BMIGSCR" Text="Chrom-gesamt im Buhnenfeld, Tages-Minimum" Unit="mg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="gsCr" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXGSCR" Text="Chrom-gesamt im Buhnenfeld, Tagesmittelwert" Unit="mg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="gsCr" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXGSCR" Text="Chrom-gesamt im Buhnenfeld, Tages-Maximum" Unit="mg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="gsCr" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BMIGLCR" Text="Chrom-gelöst im Buhnenfeld, Tages-Minimum" Unit="mg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="glCr" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXGLCR" Text="Chrom-gelöst im Buhnenfeld, Tagesmittelwert" Unit="mg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="glCr" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXGLCR" Text="Chrom-gelöst im Buhnenfeld, Tages-Maximum" Unit="mg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="glCr" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BMIGSFE" Text="Eisen-gesamt im Buhnenfeld, Tages-Minimum" Unit="mg/l" Format="F8.1" Help="" Group="Schwermetalle" Quantity="gsFe" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXGSFE" Text="Eisen-gesamt im Buhnenfeld, Tagesmittelwert" Unit="mg/l" Format="F8.1" Help="" Group="Schwermetalle" Quantity="gsFe" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXGSFE" Text="Eisen-gesamt im Buhnenfeld, Tages-Maximum" Unit="mg/l" Format="F8.1" Help="" Group="Schwermetalle" Quantity="gsFe" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BMIGLFE" Text="Eisen-gelöst im Buhnenfeld, Tages-Minimum" Unit="mg/l" Format="F8.1" Help="" Group="Schwermetalle" Quantity="glFe" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXGLFE" Text="Eisen-gelöst im Buhnenfeld, Tagesmittelwert" Unit="mg/l" Format="F8.1" Help="" Group="Schwermetalle" Quantity="glFe" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXGLFE" Text="Eisen-gelöst im Buhnenfeld, Tages-Maximum" Unit="mg/l" Format="F8.1" Help="" Group="Schwermetalle" Quantity="glFe" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BMIGSCU" Text="Kupfer-gesamt im Buhnenfeld, Tages-Minimum" Unit="mg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="gsCu" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXGSCU" Text="Kupfer-gesamt im Buhnenfeld, Tagesmittelwert" Unit="mg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="gsCu" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXGSCU" Text="Kupfer-gesamt im Buhnenfeld, Tages-Maximum" Unit="mg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="gsCu" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BMIGLCU" Text="Kupfer-gelöst im Buhnenfeld, Tages-Minimum" Unit="mg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="glCu" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXGLCU" Text="Kupfer-gelöst im Buhnenfeld, Tagesmittelwert" Unit="mg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="glCu" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXGLCU" Text="Kupfer-gelöst im Buhnenfeld, Tages-Maximum" Unit="mg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="glCu" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BMIGSMN" Text="Mangan-gesamt im Buhnenfeld, Tages-Minimum" Unit="mg/l" Format="F8.1" Help="" Group="Schwermetalle" Quantity="gsMn" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXGSMN" Text="Mangan-gesamt im Buhnenfeld, Tagesmittelwert" Unit="mg/l" Format="F8.1" Help="" Group="Schwermetalle" Quantity="gsMn" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXGSMN" Text="Mangan-gesamt im Buhnenfeld, Tages-Maximum" Unit="mg/l" Format="F8.1" Help="" Group="Schwermetalle" Quantity="gsMn" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BMIGLMN" Text="Mangan-gelöst im Buhnenfeld, Tages-Minimum" Unit="mg/l" Format="F8.1" Help="" Group="Schwermetalle" Quantity="glMn" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXGLMN" Text="Mangan-gelöst im Buhnenfeld, Tagesmittelwert" Unit="mg/l" Format="F8.1" Help="" Group="Schwermetalle" Quantity="glMn" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXGLMN" Text="Mangan-gelöst im Buhnenfeld, Tages-Maximum" Unit="mg/l" Format="F8.1" Help="" Group="Schwermetalle" Quantity="glMn" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BMIGSNI" Text="Nickel-gesamt im Buhnenfeld, Tages-Minimum" Unit="mg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="gsNi" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXGSNI" Text="Nickel-gesamt im Buhnenfeld, Tagesmittelwert" Unit="mg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="gsNi" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXGSNI" Text="Nickel-gesamt im Buhnenfeld, Tages-Maximum" Unit="mg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="gsNi" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BMIGLNI" Text="Nickel-gelöst im Buhnenfeld, Tages-Minimum" Unit="mg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="glNi" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXGLNI" Text="Nickel-gelöst im Buhnenfeld, Tagesmittelwert" Unit="mg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="glNi" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXGLNI" Text="Nickel-gelöst im Buhnenfeld, Tages-Maximum" Unit="mg/l" Format="F6.2" Help="" Group="Schwermetalle" Quantity="glNi" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BMIGSHG" Text="Quecksilber-gesamt im Buhnenfeld, Tages-Minimum" Unit="mg/l" Format="F7.3" Help="" Group="Schwermetalle" Quantity="gsHg" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXGSHG" Text="Quecksilber-gesamt im Buhnenfeld, Tagesmittelwert" Unit="mg/l" Format="F7.3" Help="" Group="Schwermetalle" Quantity="gsHg" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXGSHG" Text="Quecksilber-gesamt im Buhnenfeld, Tages-Maximum" Unit="mg/l" Format="F7.3" Help="" Group="Schwermetalle" Quantity="gsHg" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BMIGLHG" Text="Quecksilber-gelöst im Buhnenfeld, Tages-Minimum" Unit="mg/l" Format="F7.3" Help="" Group="Schwermetalle" Quantity="glHg" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXGLHG" Text="Quecksilber-gelöst im Buhnenfeld, Tagesmittelwert" Unit="mg/l" Format="F7.3" Help="" Group="Schwermetalle" Quantity="glHg" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXGLHG" Text="Quecksilber-gelöst im Buhnenfeld, Tages-Maximum" Unit="mg/l" Format="F7.3" Help="" Group="Schwermetalle" Quantity="glHg" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BMIGSU" Text="Uran-gesamt im Buhnenfeld, Tages-Minimum" Unit="mg/l" Format="F7.3" Help="" Group="Schwermetalle" Quantity="gsU" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXGSU" Text="Uran-gesamt im Buhnenfeld, Tagesmittelwert" Unit="mg/l" Format="F7.3" Help="" Group="Schwermetalle" Quantity="gsU" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXGSU" Text="Uran-gesamt im Buhnenfeld, Tages-Maximum" Unit="mg/l" Format="F7.3" Help="" Group="Schwermetalle" Quantity="gsU" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BMIGLU" Text="Uran-gelöst im Buhnenfeld, Tages-Minimum" Unit="mg/l" Format="F7.3" Help="" Group="Schwermetalle" Quantity="glU" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXGLU" Text="Uran-gelöst im Buhnenfeld, Tagesmittelwert" Unit="mg/l" Format="F7.3" Help="" Group="Schwermetalle" Quantity="glU" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXGLU" Text="Uran-gelöst im Buhnenfeld, Tages-Maximum" Unit="mg/l" Format="F7.3" Help="" Group="Schwermetalle" Quantity="glU" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BMIGSZN" Text="Zink-gesamt im Buhnenfeld, Tages-Minimum" Unit="mg/l" Format="F8.1" Help="" Group="Schwermetalle" Quantity="gsZn" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXGSZN" Text="Zink-gesamt im Buhnenfeld, Tagesmittelwert" Unit="mg/l" Format="F8.1" Help="" Group="Schwermetalle" Quantity="gsZn" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXGSZN" Text="Zink-gesamt im Buhnenfeld, Tages-Maximum" Unit="mg/l" Format="F8.1" Help="" Group="Schwermetalle" Quantity="gsZn" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BMIGLZN" Text="Zink-gelöst im Buhnenfeld, Tages-Minimum" Unit="mg/l" Format="F8.1" Help="" Group="Schwermetalle" Quantity="glZn" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXGLZN" Text="Zink-gelöst im Buhnenfeld, Tagesmittelwert" Unit="mg/l" Format="F8.1" Help="" Group="Schwermetalle" Quantity="glZn" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXGLZN" Text="Zink-gelöst im Buhnenfeld, Tages-Maximum" Unit="mg/l" Format="F8.1" Help="" Group="Schwermetalle" Quantity="glZn" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BMIGSAS" Text="Arsen-gesamt im Buhnenfeld, Tages-Minimum" Unit="mg/l" Format="F5.1" Help="" Group="Schwermetalle" Quantity="gsAs" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXGSAS" Text="Arsen-gesamt im Buhnenfeld, Tagesmittelwert" Unit="mg/l" Format="F5.1" Help="" Group="Schwermetalle" Quantity="gsAs" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXGSAS" Text="Arsen-gesamt im Buhnenfeld, Tages-Maximum" Unit="mg/l" Format="F5.1" Help="" Group="Schwermetalle" Quantity="gsAs" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BMIGLAS" Text="Arsen-gelöst im Buhnenfeld, Tages-Minimum" Unit="mg/l" Format="F5.1" Help="" Group="Schwermetalle" Quantity="glAs" Aggregat="Min" />'
   write(1, '(A)') '  <Parameter Ident="BXGLAS" Text="Arsen-gelöst im Buhnenfeld, Tagesmittelwert" Unit="mg/l" Format="F5.1" Help="" Group="Schwermetalle" Quantity="glAs" Aggregat="Avg" />'
   write(1, '(A)') '  <Parameter Ident="BMXGLAS" Text="Arsen-gelöst im Buhnenfeld, Tages-Maximum" Unit="mg/l" Format="F5.1" Help="" Group="Schwermetalle" Quantity="glAs" Aggregat="Max" />'
   write(1, '(A)') '  <Parameter Ident="BXAKG" Text="Gesamtbiomasse der Algen im Buhnenfeld" Unit="mgC/l" Format="F6.2" Help="" Group="Buhne" Quantity="AKG" />'
   write(1, '(A)') '  <Parameter Ident="BXDALG" Text="mittl. Produktionsrate der Algen im Buhnenfeld" Unit="1/d" Format="F8.5" Help="" Group="Buhne" Quantity="DALG" />'
   write(1, '(A)') '  <Parameter Ident="BXDAA" Text="mittl. Respirationsrate d.Algen im Buhnenfeld" Unit="1/d" Format="F8.5" Help="" Group="Buhne" Quantity="DAA" />'
   write(1, '(A)') '  <Parameter Ident="BXAMOR" Text="mittl. Mortalitätsrate d. Algen im Buhnenfeld" Unit="1/d" Format="F8.5" Help="" Group="Buhne" Quantity="AMOR" />'
   write(1, '(A)') '  <Parameter Ident="BXSEDA" Text="mit Sedimentationsrate d. Algen im Buhnenfeld" Unit="1/d" Format="F8.5" Help="" Group="Buhne" Quantity="SEDA" />'
   write(1, '(A)') '  <Parameter Ident="BXALGZ" Text="mittl. Grazingrate d. Zooplankton im Buhnenfeld" Unit="1/d" Format="F8.5" Help="" Group="Buhne" Quantity="ALGZ" />'
   write(1, '(A)') '  <Parameter Ident="BXALDR" Text="mittl. Grazingrate d. Dreissena im Buhnenfeld" Unit="1/d" Format="F8.5" Help="" Group="Buhne" Quantity="ALDR" />'
   write(1, '(A)') '  <Parameter Ident="BXDRPF" Text="mittl. Pseudofacesanteil d. Dreissena im Buhnenfeld" Unit="%" Format="F6.2" Help="" Group="Buhne" Quantity="DRPF" />'
   write(1, '(A)') '  <Parameter Ident="BTPMAX" Text="Nährstoffabhängigkeit im Buhnenfeld bezogen auf Hellphase " Unit="[0..1]" Format="F5.2" Help="" Group="Buhne" Quantity="" />'
   write(1, '(A)') '  <Parameter Ident="BXVKG" Text="Verhältnis Kieselalg./Grünalg. im Buhnenfeld" Unit="[0..1]" Format="F5.2" Help="" Group="Buhne" Quantity="VKG" />'
   write(1, '(A)') '  <Parameter Ident="BXANTB" Text="Anteil Blaualgen am Chla im Buhnenfeld" Unit="[0..1]" Format="F5.2" Help="" Group="Buhne" Quantity="ANTB" />'
   write(1, '(A)') '  <Parameter Ident="BXALCO" Text="Algenverlust d. Chorophium im Buhnenfeld" Unit="" Format="F10.8" Help="" Group="Buhne" Quantity="ALCO" />'
   write(1, '(A)') '  <Parameter Ident="BXFIK" Text="Lichtabhängigkeit der Algenprod. im Buhnenfeld, bezogen auf Hellphase" Unit="[0..1]" Format="F5.2" Help="" Group="Buhne" Quantity="FIK" />'
   write(1, '(A)') '  <Parameter Ident="BXFIG" Text="Extinktionskoeffizient im Buhnenfeld" Unit="1/m" Format="F5.2" Help="" Group="Buhne" Quantity="FIG" />'
   write(1, '(A)') '  <Parameter Ident="BXFIB" Text="leer" Unit="" Format="F5.2" Help="" Group="Buhne" Quantity="FIB" />'
   write(1, '(A)') '  <Parameter Ident="BXKMUE" Text="Bruttowachstumsrate der Kieselalgen im Buhnenfeld" Unit="1/d" Format="F6.3" Help="" Group="Buhne" Quantity="KMUE" />'
   write(1, '(A)') '  <Parameter Ident="BXGMUE" Text="Bruttowachstumsrate der Grünalgen im Buhnenfeld" Unit="1/d" Format="F6.3" Help="" Group="Buhne" Quantity="GMUE" />'
   write(1, '(A)') '  <Parameter Ident="BXBMUE" Text="Bruttowachstumsrate der Blaualgen im Buhnenfeld" Unit="1/d" Format="F6.3" Help="" Group="Buhne" Quantity="BMUE" />'
   write(1, '(A)') '  <Parameter Ident="BXHEK" Text="Lichthemmung der Kieselalgen im Buhnenfeld" Unit="[0..1]" Format="F6.3" Help="" Group="Buhne" Quantity="HEK" />'
   write(1, '(A)') '  <Parameter Ident="BXHEG" Text="Lichthemmung der Grünalgen im Buhnenfeld" Unit="[0..1]" Format="F6.3" Help="" Group="Buhne" Quantity="HEG" />'
   write(1, '(A)') '  <Parameter Ident="BXHEB" Text="Lichthemmung der Blaualgen im Buhnenfeld" Unit="[0..1]" Format="F6.3" Help="" Group="Buhne" Quantity="HEB" />'
   write(1, '(A)') '  <Parameter Ident="BXKRE" Text="Respirationsrate der Kieselalgen im Buhnenfeld" Unit="1/d" Format="F6.3" Help="" Group="Buhne" Quantity="KRE" />'
   write(1, '(A)') '  <Parameter Ident="BXGRE" Text="Respirationsrate der Grünalgen im Buhnenfeld" Unit="1/d" Format="F6.3" Help="" Group="Buhne" Quantity="GRE" />'
   write(1, '(A)') '  <Parameter Ident="BXBRE" Text="Respirationsrate der Blaualgen im Buhnenfeld" Unit="1/d" Format="F6.3" Help="" Group="Buhne" Quantity="BRE" />'
   write(1, '(A)') '  <Parameter Ident="BXCHLK" Text="Chla-Gehalt der Kieselalgen im Buhnenfeld" Unit="µg/l" Format="F6.1" Help="" Group="Buhne" Quantity="CHLK" />'
   write(1, '(A)') '  <Parameter Ident="BXCHLG" Text="Chla-Gehalt der Grünalgen im Buhnenfeld" Unit="µg/l" Format="F6.1" Help="" Group="Buhne" Quantity="CHLG" />'
   write(1, '(A)') '  <Parameter Ident="BXCHLB" Text="Chla-Gehalt der Blaualgen im Buhnenfeld" Unit="µg/l" Format="F6.1" Help="" Group="Buhne" Quantity="CHLB" />'
   write(1, '(A)') '  <Parameter Ident="bxFlN3" Text="Nitratänderung im Wasserkörper des Buhnenfelds durch das Sediment" Unit="mgN/(l*h)" Format="F10.7" Help="" Group="Buhne" Quantity="" />'
   write(1, '(A)') '  <Parameter Ident="bxJNO3" Text="Nitratflux Wasser/Sediment (-)" Unit="gN/(m2*d)" Format="F10.8" Help="" Group="Buhne" Quantity="" />'
   write(1, '(A)') '  <Parameter Ident="bxJNH4" Text="Ammoniumflux Wasser/Sediment (-)" Unit="gN/(m2*d)" Format="F10.8" Help="" Group="Buhne" Quantity="" />'
   write(1, '(A)') '  <Parameter Ident="bxBetN" Text="AmmoniumFlux Wasser Sediment(-)" Unit="mgN/(l*h)" Format="F8.6" Help="" Group="Buhne" Quantity="" />'
   write(1, '(A)') '  <Parameter Ident="bxJPO4" Text="P-Flux Wasser/Sediment(-)" Unit="gP/(m2*d)" Format="F10.8" Help="" Group="Buhne" Quantity="" />'
   write(1, '(A)') '  <Parameter Ident="bxJSi" Text="Si-Flux Wasser/Sediment(-)" Unit="gSi/(m2*d)" Format="F10.8" Help="" Group="Buhne" Quantity="" />'
   write(1, '(A)') '  <Parameter Ident="bxJO2" Text="O2Flux Wasser/Sediment(+)" Unit="gO2/(m2*d)" Format="F10.8" Help="" Group="Buhne" Quantity="" />'
   write(1, '(A)') '</ParamSetDef>'
   
   write(1, '(A)') '</GerrisParam>'
   
   close(1)
end subroutine ErgebMParam

